// Code generated by "stringer -type=LSPMessageType"; DO NOT EDIT.

package li

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LSPError-1]
	_ = x[LSPWarning-2]
	_ = x[LSPInfo-3]
	_ = x[LSPLog-4]
}

const _LSPMessageType_name = "LSPErrorLSPWarningLSPInfoLSPLog"

var _LSPMessageType_index = [...]uint8{0, 8, 18, 25, 31}

func (i LSPMessageType) String() string {
	i -= 1
	if i >= LSPMessageType(len(_LSPMessageType_index)-1) {
		return "LSPMessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LSPMessageType_name[_LSPMessageType_index[i]:_LSPMessageType_index[i+1]]
}
